package enigma

import (
	"testing"
)

// Dönitz message:
// https://enigma.hoerenberg.com/index.php?cat=The%20U534%20messages&page=P1030681
// https://www.cryptomuseum.com/crypto/enigma/msg/p1030681.htm
func TestDonitzMessage(t *testing.T) {
	c := Config{
		Plugboard: "AE BF CM DQ HU JN LX PR SZ VW",
		Rotors: []RotorInfo{
			{
				ID:       "Beta",
				Ring:     "A",
				Position: "Y",
			},
			{
				ID:       "V",
				Ring:     "A",
				Position: "O",
			},
			{
				ID:       "VI",
				Ring:     "E",
				Position: "S",
			},
			{
				ID:       "VIII",
				Ring:     "L",
				Position: "Z",
			},
		},
		ReflectorID: "C-thin",
	}

	tp := TestPair{
		Ciphertext: "LANOTCTOUARBBFPMHPHGCZXTDYGAHGUFXGEWKBLKGJWLQXXTGPJJAVTOCKZFSLPPQIHZFXOEBWIIEKFZLCLOAQJULJOYHSSMBBGWHZANVOIIPYRBRTDJQDJJOQKCXWDNBBTYVXLYTAPGVEATXSONPNYNQFUDBBHHVWEPYEYDOHNLXKZDNWRHDUWUJUMWWVIIWZXIVIUQDRHYMNCYEFUAPNHOTKHKGDNPSAKNUAGHJZSMJBMHVTREQEDGXHLZWIFUSKDQVELNMIMITHBHDBWVHDFYHJOQIHORTDJDBWXEMEAYXGYQXOHFDMYUXXNOJAZRSGHPLWMLRECWWUTLRTTVLBHYOORGLGOWUXNXHMHYFAACQEKTHSJW",
		Plaintext:  "KRKRALLEXXFOLGENDESISTSOFORTBEKANNTZUGEBENXXICHHABEFOLGELNBEBEFEHLERHALTENXXJANSTERLEDESBISHERIGXNREICHSMARSCHALLSJGOERINGJSETZTDERFUEHRERSIEYHVRRGRZSSADMIRALYALSSEINENNACHFOLGEREINXSCHRIFTLSCHEVOLLMACHTUNTERWEGSXABSOFORTSOLLENSIESAEMTLICHEMASSNAHMENVERFUEGENYDIESICHAUSDERGEGENWAERTIGENLAGEERGEBENXGEZXREICHSLEITEIKKTULPEKKJBORMANNJXXOBXDXMMMDURNHFKSTXKOMXADMXUUUBOOIEXKP",
	}

	e, err := New(c)
	if err != nil {
		t.Fatal(err)
	}

	plaintext := e.FeedString(tp.Ciphertext)
	if plaintext != tp.Plaintext {
		t.Fatalf("wrong decrypt 'Dönitz message'")
	}
}
